/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MbPnregistryList {
    }
}
declare global {
    interface HTMLMbPnregistryListElement extends Components.MbPnregistryList, HTMLStencilElement {
    }
    var HTMLMbPnregistryListElement: {
        prototype: HTMLMbPnregistryListElement;
        new (): HTMLMbPnregistryListElement;
    };
    interface HTMLElementTagNameMap {
        "mb-pnregistry-list": HTMLMbPnregistryListElement;
    }
}
declare namespace LocalJSX {
    interface MbPnregistryList {
    }
    interface IntrinsicElements {
        "mb-pnregistry-list": MbPnregistryList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mb-pnregistry-list": LocalJSX.MbPnregistryList & JSXBase.HTMLAttributes<HTMLMbPnregistryListElement>;
        }
    }
}
